# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20170225_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='transactions',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bikes.Customer'),
        ),
    ]
