# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_auto_20170225_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
