# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_auto_20170227_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.Customer'),
        ),
    ]
