# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_auto_20170227_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='completed',
        ),
    ]
