# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_remove_repair_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repair',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='repair',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
