# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0015_transaction_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=300)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bikes.Customer')),
                ('items', models.ManyToManyField(blank=True, to='bikes.Item')),
            ],
        ),
    ]
